### ISSUE TITLE
How to explain that most of witches were in middling class?

### ISSUE THREAD

**Issue by Chicone1003** [Chicone1003/BeatPython#1]
It was very weird that middle class should be not poor and maybe in a relatively high status. But why they were accused? It seems unreasonable! 
Maybe because people could get money from died witches?( I had read a little about that but not strong evidence) Maybe they were not rich as we thought?
What do you guys think?!

**Comment by rosyshu** [comment]
Some comments from the Miller Joyce may help:
Socio-economic status
The general stereotype is that those accused of witchcraft were poorer than their accusers: resentment, anger etc. In Scotland the majority of accused were neither the richest nor the poorest. They tended to be from farming, crafts or other 'middling' people. In this context 'middling' does not equate to our modern definition of middle class. Again the statistic cannot be absolute: only 11% of the total accused indicated socio-economic status. What was indicated was, that for the most part, the accused lived within their settled communities. High court/central trials (those with better records) had a slightly higher number (18%) of 'elite' suspects - possibly indicating that they were able to afford/request a central trial. Local trials (most records of which did not survive) appear to have had a higher percentage (12%) of very poor suspects. These are small percentages: As the majority did not have their socio-economic status recorded specifically and that the majority of trials were 'local' it was calculated that the status of most people tried locally would reflect the socio-economic level of their communities: 4% elite (very high wealth and status); 84% middling or lower (reflecting burgh and rural status) and 12% very poor. It is important to note that for Scotland in the sixteenth and seventeenth centuries the majority of households were middling to lower. This does not support the general stereotype of a suspect being marginalised due to their lack of income but that they were very much part of their communities and of average (=middling) socio-economic status. (p61-62)

**Comment by Chicone1003** [comment]
Thanks Hong!!It was exactly what we wanted! We could explore more about it. Maybe we could link it to Capitalism!
